import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatDateTime } from "../hooks/useLiveData";
import { getDateRange, formatRangeLabel, type ReportPeriod } from "./reportDateRange";
import {
  buildDriverFleetRows,
  buildDriverOverviewStats,
  buildDriverPerformanceRows,
  buildDriverReportStats,
  fetchSupervisorExportData,
  filterDeliveriesForRange,
  filterReportsForRange,
  filterRoutesForRange,
  formatReportType,
  labelDriverStatus,
  labelReportStatus,
  labelRouteStatus,
  routeAssignedAt,
  routeCompletedAt,
} from "./supervisorExportData";

const MARGIN = 14;
const PAGE_WIDTH = 210;

type AutoTableDoc = jsPDF & { lastAutoTable: { finalY: number } };

function truncate(value: string, max = 80) {
  const trimmed = value.trim();
  if (trimmed.length <= max) return trimmed;
  return `${trimmed.slice(0, max - 1)}…`;
}

function addSectionTitle(doc: jsPDF, title: string, y: number) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(17, 24, 39);
  doc.text(title, MARGIN, y);
  doc.setDrawColor(229, 231, 235);
  doc.line(MARGIN, y + 2, PAGE_WIDTH - MARGIN, y + 2);
  return y + 8;
}

function addKeyValueGrid(doc: jsPDF, rows: Array<[string, string]>, startY: number) {
  doc.setFontSize(10);
  let y = startY;

  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(75, 85, 99);
    doc.text(label, MARGIN, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(17, 24, 39);
    doc.text(value, MARGIN + 68, y);
    y += 6;
  });

  return y + 4;
}

function applyFooters(doc: jsPDF, exportTimestamp: Date) {
  const pageCount = doc.getNumberOfPages();
  const pageHeight = doc.internal.pageSize.height;

  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text("Generated by ECOLOOP System", MARGIN, pageHeight - 8);
    doc.text(formatDateTime(exportTimestamp.toISOString()), PAGE_WIDTH / 2, pageHeight - 8, { align: "center" });
    doc.text(`Page ${page} of ${pageCount}`, PAGE_WIDTH - MARGIN, pageHeight - 8, { align: "right" });
  }
}

export async function exportSupervisorPdf(options: {
  supervisorName: string;
  period: ReportPeriod;
  customStart?: string;
  customEnd?: string;
}) {
  const exportTimestamp = new Date();
  const range = getDateRange(options.period, options.customStart, options.customEnd);
  const data = await fetchSupervisorExportData();

  const routesInRange = filterRoutesForRange(data.routes, range);
  const reportsInRange = filterReportsForRange(data.reports, range);
  const deliveriesInRange = filterDeliveriesForRange(data.deliveries, range);
  const driverOverview = buildDriverOverviewStats(data.drivers, routesInRange, deliveriesInRange);
  const driverRows = buildDriverPerformanceRows(
    data.drivers,
    routesInRange,
    deliveriesInRange,
    reportsInRange,
    data.vehicles,
  );
  const driverReportStats = buildDriverReportStats(reportsInRange);
  const driverFleetRows = buildDriverFleetRows(data.drivers, data.routes, data.vehicles, data.vehicleLocations);
  const driverById = new Map(data.drivers.map((driver) => [String(driver.id), driver.name]));

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = MARGIN;

  doc.setFillColor(16, 185, 129);
  doc.rect(0, 0, PAGE_WIDTH, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(data.organizationName, MARGIN, 12);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Driver Operations Summary Report", MARGIN, 19);
  doc.setFontSize(9);
  doc.text(`Reporting Period: ${range.label} (${formatRangeLabel(range)})`, MARGIN, 25);

  y = 36;
  doc.setTextColor(17, 24, 39);
  y = addKeyValueGrid(
    doc,
    [
      ["Supervisor", options.supervisorName || "Not recorded"],
      ["Generated", formatDateTime(exportTimestamp.toISOString())],
      ["Period Type", range.label],
      ["Date Range", formatRangeLabel(range)],
    ],
    y,
  );

  y = addSectionTitle(doc, "1. Driver Statistics Overview", y);
  y = addKeyValueGrid(
    doc,
    [
      ["Total Drivers", String(driverOverview.totalDrivers)],
      ["Available Drivers", String(driverOverview.available)],
      ["Drivers On Active Route", String(driverOverview.onRoute)],
      ["Drivers With Assignments", String(driverOverview.withAssignments)],
      ["Completed Collections", String(driverOverview.completedCollections)],
      ["Route Completion Rate", `${driverOverview.completionRate}%`],
    ],
    y,
  );

  y = addSectionTitle(doc, "2. Driver Performance", y);
  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [
      [
        "Driver",
        "Status",
        "Vehicle",
        "Routes",
        "Completed",
        "Pending",
        "Collections",
        "Reports",
        "Completion %",
      ],
    ],
    body:
      driverRows.length > 0
        ? driverRows.map((row) => [
            row.name,
            labelDriverStatus(row.status),
            truncate(row.vehicleLabel, 24),
            String(row.assigned),
            String(row.completed),
            String(row.pending),
            String(row.collectionsCompleted),
            String(row.reportsFiled),
            `${row.completionPct}%`,
          ])
        : [["No drivers found", "—", "—", "0", "0", "0", "0", "0", "0%"]],
    styles: { fontSize: 7.5, cellPadding: 2 },
    headStyles: { fillColor: [16, 185, 129], textColor: 255 },
    theme: "grid",
  });
  y = (doc as AutoTableDoc).lastAutoTable.finalY + 8;

  y = addSectionTitle(doc, "3. Driver Reports and Issues", y);
  y = addKeyValueGrid(
    doc,
    [
      ["Driver Reports Submitted", String(driverReportStats.total)],
      ["Pending Reports", String(driverReportStats.pending)],
      ["In Progress Reports", String(driverReportStats.inProgress)],
      ["Resolved Reports", String(driverReportStats.resolved)],
    ],
    y,
  );

  const driverReportsInRange = reportsInRange.filter((report) => report.driver_id != null);
  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [["Driver", "Report Type", "Description", "Status", "Date Submitted", "Assigned Personnel"]],
    body:
      driverReportsInRange.length > 0
        ? driverReportsInRange.map((report) => [
            driverById.get(String(report.driver_id)) ?? report.reported_by ?? "Unknown driver",
            formatReportType(report),
            truncate(report.description ?? report.type ?? "—", 50),
            labelReportStatus(report.status),
            formatDateTime(report.created_at),
            report.assigned_to ?? "Unassigned",
          ])
        : [["No driver reports in selected period", "—", "—", "—", "—", "—"]],
    styles: { fontSize: 8, cellPadding: 2, overflow: "linebreak" },
    headStyles: { fillColor: [59, 130, 246], textColor: 255 },
    theme: "grid",
  });
  y = (doc as AutoTableDoc).lastAutoTable.finalY + 8;

  if (y > 240) {
    doc.addPage();
    y = MARGIN;
  }

  y = addSectionTitle(doc, "4. Driver Fleet Activity", y);
  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [["Driver", "Status", "Assigned Vehicle", "Current Route", "Last Location", "Last Updated"]],
    body:
      driverFleetRows.length > 0
        ? driverFleetRows.map((row) => [
            row.name,
            labelDriverStatus(row.status),
            truncate(row.vehicle, 22),
            truncate(row.currentRoute, 24),
            row.lastLocation,
            row.lastUpdated ? formatDateTime(row.lastUpdated) : "Not recorded",
          ])
        : [["No drivers found", "—", "—", "—", "—", "—"]],
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [107, 114, 128], textColor: 255 },
    theme: "grid",
  });
  y = (doc as AutoTableDoc).lastAutoTable.finalY + 8;

  if (y > 230) {
    doc.addPage();
    y = MARGIN;
  }

  const driverRoutesInRange = routesInRange
    .filter((route) => route.driver_id != null)
    .sort((a, b) => {
      const nameA = driverById.get(String(a.driver_id)) ?? "";
      const nameB = driverById.get(String(b.driver_id)) ?? "";
      return nameA.localeCompare(nameB);
    });

  y = addSectionTitle(doc, "5. Route Performance by Driver", y);
  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [["Driver", "Route Name", "Status", "Date Assigned", "Date Completed"]],
    body:
      driverRoutesInRange.length > 0
        ? driverRoutesInRange.map((route) => [
            driverById.get(String(route.driver_id)) ?? "Unassigned",
            route.name,
            labelRouteStatus(route.status),
            routeAssignedAt(route) ? formatDateTime(routeAssignedAt(route)) : "Not recorded",
            routeCompletedAt(route) ? formatDateTime(routeCompletedAt(route)) : "—",
          ])
        : [["No driver routes in selected period", "—", "—", "—", "—"]],
    styles: { fontSize: 9, cellPadding: 2.5 },
    headStyles: { fillColor: [16, 185, 129], textColor: 255 },
    theme: "grid",
  });

  applyFooters(doc, exportTimestamp);

  const safeDate = exportTimestamp.toISOString().slice(0, 10);
  doc.save(`${data.organizationName.replace(/\s+/g, "-")}-driver-operations-report-${safeDate}.pdf`);
}
