import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatDateTime, normalizeStatus } from "../hooks/useLiveData";
import { getDateRange, formatRangeLabel, type ReportPeriod } from "./reportDateRange";
import {
  fetchSupervisorExportData,
  filterDeliveriesForRange,
  filterReportsForRange,
  filterRoutesForRange,
  formatReportType,
  labelDriverStatus,
  labelReportStatus,
  labelRouteStatus,
  routeAssignedAt,
  routeCompletedAt,
  type SupervisorExportDelivery,
  type SupervisorExportReport,
  type SupervisorExportRoute,
} from "./supervisorExportData";

const MARGIN = 14;
const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

type AutoTableDoc = jsPDF & { lastAutoTable: { finalY: number } };

function truncate(value: string, max = 64) {
  const trimmed = value.trim();
  if (trimmed.length <= max) return trimmed;
  return `${trimmed.slice(0, max - 1)}...`;
}

function formatDate(value?: string | null) {
  if (!value) return "Not recorded";
  return new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value));
}

function formatNumber(value: number, suffix = "") {
  if (!Number.isFinite(value)) return suffix ? `0${suffix}` : "0";
  return `${Math.round(value * 10) / 10}${suffix}`;
}

function routeMinutes(route: SupervisorExportRoute) {
  const plannedMinutes = Number(route.duration_minutes);
  if (Number.isFinite(plannedMinutes) && plannedMinutes > 0) return plannedMinutes;

  const start = route.started_at ?? routeAssignedAt(route);
  const end = routeCompletedAt(route);
  if (!start || !end) return 0;

  const minutes = (new Date(end).getTime() - new Date(start).getTime()) / 60000;
  return Number.isFinite(minutes) && minutes > 0 ? minutes : 0;
}

function isRouteCompleted(route: SupervisorExportRoute) {
  return normalizeStatus(route.status) === "completed";
}

function isDeliveryCompleted(delivery: SupervisorExportDelivery) {
  return normalizeStatus(delivery.status) === "completed";
}

function isDeliveryMissed(delivery: SupervisorExportDelivery, completedRouteIds: Set<string>) {
  const status = normalizeStatus(delivery.status);
  return ["missed", "skipped", "failed", "cancelled"].includes(status) ||
    (!isDeliveryCompleted(delivery) && completedRouteIds.has(String(delivery.route_id)));
}

function isOpenIncident(report: SupervisorExportReport) {
  return normalizeStatus(report.status) !== "resolved";
}

function priorityRank(report: SupervisorExportReport) {
  const priority = normalizeStatus(report.priority);
  if (priority === "critical") return 3;
  if (priority === "high") return 2;
  if (priority === "medium") return 1;
  return 0;
}

function applyFooters(doc: jsPDF, exportTimestamp: Date) {
  const pageCount = doc.getNumberOfPages();

  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text("Generated by ECOLOOP System", MARGIN, PAGE_HEIGHT - 8);
    doc.text(formatDateTime(exportTimestamp.toISOString()), PAGE_WIDTH / 2, PAGE_HEIGHT - 8, { align: "center" });
    doc.text(`Page ${page} of ${pageCount}`, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 8, { align: "right" });
  }
}

function addHeader(doc: jsPDF, organizationName: string, rangeLabel: string, exportTimestamp: Date) {
  doc.setFillColor(16, 185, 129);
  doc.rect(0, 0, PAGE_WIDTH, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(organizationName, MARGIN, 12);
  doc.setFontSize(11);
  doc.text("Driver Performance Brief", MARGIN, 20);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.text(`Period: ${rangeLabel}`, MARGIN, 26);
  doc.text(`Generated: ${formatDateTime(exportTimestamp.toISOString())}`, PAGE_WIDTH - MARGIN, 26, { align: "right" });
}

function addKpiCard(doc: jsPDF, x: number, y: number, width: number, label: string, value: string, note: string) {
  doc.setFillColor(249, 250, 251);
  doc.setDrawColor(229, 231, 235);
  doc.roundedRect(x, y, width, 22, 2, 2, "FD");
  doc.setTextColor(75, 85, 99);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.text(label.toUpperCase(), x + 3, y + 6);
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(15);
  doc.text(value, x + 3, y + 14);
  doc.setTextColor(107, 114, 128);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.text(truncate(note, 22), x + 3, y + 19);
}

function sectionTitle(doc: jsPDF, title: string, y: number) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10.5);
  doc.setTextColor(17, 24, 39);
  doc.text(title, MARGIN, y);
  doc.setDrawColor(229, 231, 235);
  doc.line(MARGIN, y + 2, PAGE_WIDTH - MARGIN, y + 2);
  return y + 7;
}

export async function exportSupervisorPdf(options: {
  supervisorName: string;
  driverId: string | number;
  period: ReportPeriod;
  customStart?: string;
  customEnd?: string;
}) {
  const exportTimestamp = new Date();
  const range = getDateRange(options.period, options.customStart, options.customEnd);
  const data = await fetchSupervisorExportData();
  const driver = data.drivers.find((item) => String(item.id) === String(options.driverId));

  if (!driver) {
    throw new Error("Selected driver could not be found.");
  }

  const driverKey = String(driver.id);
  const routesInRange = filterRoutesForRange(data.routes, range).filter((route) => String(route.driver_id) === driverKey);
  const routeIds = new Set(routesInRange.map((route) => String(route.id)));
  const completedRouteIds = new Set(routesInRange.filter(isRouteCompleted).map((route) => String(route.id)));
  const deliveriesInRange = filterDeliveriesForRange(data.deliveries, range).filter(
    (delivery) => String(delivery.driver_id) === driverKey || routeIds.has(String(delivery.route_id)),
  );
  const reportsInRange = filterReportsForRange(data.reports, range).filter((report) => String(report.driver_id) === driverKey);
  const assignedVehicle =
    driver.assigned_vehicle_id != null
      ? data.vehicles.find((vehicle) => String(vehicle.id) === String(driver.assigned_vehicle_id))
      : data.vehicles.find((vehicle) => String(vehicle.driver_id) === driverKey);
  const currentRoute = data.routes.find((route) => {
    const status = normalizeStatus(route.status);
    return String(route.driver_id) === driverKey && ["active", "pending", "planned"].includes(status);
  });

  const completedRoutes = routesInRange.filter(isRouteCompleted).length;
  const activeRoutes = routesInRange.filter((route) => ["active", "pending", "planned"].includes(normalizeStatus(route.status))).length;
  const routeCompletionRate = routesInRange.length > 0 ? Math.round((completedRoutes / routesInRange.length) * 100) : 0;
  const completedStops = deliveriesInRange.filter(isDeliveryCompleted).length;
  const missedStops = deliveriesInRange.filter((delivery) => isDeliveryMissed(delivery, completedRouteIds)).length;
  const pendingStops = deliveriesInRange.filter((delivery) => !isDeliveryCompleted(delivery) && !isDeliveryMissed(delivery, completedRouteIds)).length;
  const activeHours = routesInRange.reduce((sum, route) => sum + routeMinutes(route), 0) / 60;
  const distanceKm = routesInRange.reduce((sum, route) => sum + (Number(route.distance_km) || 0), 0);
  const openIncidents = reportsInRange.filter(isOpenIncident).length;
  const highPriorityIncidents = reportsInRange.filter((report) => priorityRank(report) >= 2).length;

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  addHeader(doc, data.organizationName, formatRangeLabel(range), exportTimestamp);

  let y = 40;
  doc.setTextColor(17, 24, 39);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(driver.name, MARGIN, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(75, 85, 99);
  y += 6;
  doc.text(`Status: ${labelDriverStatus(driver.status)}`, MARGIN, y);
  doc.text(`Vehicle: ${assignedVehicle ? `${assignedVehicle.code} - ${assignedVehicle.label}` : "Unassigned"}`, MARGIN + 52, y);
  y += 5;
  doc.text(`Current assignment: ${currentRoute?.name ?? "No active route"}`, MARGIN, y);
  doc.text(`Exported by: ${options.supervisorName || "Not recorded"}`, MARGIN + 92, y);

  y += 10;
  const cardGap = 4;
  const cardWidth = (CONTENT_WIDTH - cardGap * 3) / 4;
  addKpiCard(doc, MARGIN, y, cardWidth, "Routes", `${completedRoutes}/${routesInRange.length}`, `${routeCompletionRate}% complete`);
  addKpiCard(doc, MARGIN + (cardWidth + cardGap), y, cardWidth, "Active Hours", formatNumber(activeHours, "h"), "estimated route time");
  addKpiCard(doc, MARGIN + (cardWidth + cardGap) * 2, y, cardWidth, "Stops", `${completedStops}/${deliveriesInRange.length}`, `${missedStops} missed`);
  addKpiCard(doc, MARGIN + (cardWidth + cardGap) * 3, y, cardWidth, "Incidents", String(openIncidents), `${highPriorityIncidents} high priority`);

  y += 32;
  y = sectionTitle(doc, "Operational Summary", y);
  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    body: [
      ["Assigned routes", String(routesInRange.length), "Completed routes", String(completedRoutes)],
      ["Active/pending routes", String(activeRoutes), "Route completion", `${routeCompletionRate}%`],
      ["Completed stops", String(completedStops), "Pending stops", String(pendingStops)],
      ["Missed stops", String(missedStops), "Distance covered", formatNumber(distanceKm, " km")],
      ["Field issue reports", String(reportsInRange.length), "Open incidents", String(openIncidents)],
    ],
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: {
      0: { fontStyle: "bold", textColor: [75, 85, 99] },
      2: { fontStyle: "bold", textColor: [75, 85, 99] },
    },
    theme: "grid",
  });
  y = (doc as AutoTableDoc).lastAutoTable.finalY + 8;

  y = sectionTitle(doc, "Recent Route History", y);
  const recentRoutes = [...routesInRange]
    .sort((a, b) => new Date(routeAssignedAt(b) ?? 0).getTime() - new Date(routeAssignedAt(a) ?? 0).getTime())
    .slice(0, 8);

  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [["Route", "Status", "Stops", "Duration", "Distance", "Completed"]],
    body:
      recentRoutes.length > 0
        ? recentRoutes.map((route) => {
            const routeDeliveries = deliveriesInRange.filter((delivery) => String(delivery.route_id) === String(route.id));
            const routeCompletedStops = routeDeliveries.filter(isDeliveryCompleted).length;
            return [
              truncate(route.name, 34),
              labelRouteStatus(route.status),
              `${routeCompletedStops}/${routeDeliveries.length}`,
              routeMinutes(route) > 0 ? `${Math.round(routeMinutes(route))} min` : "Not recorded",
              Number(route.distance_km) > 0 ? formatNumber(Number(route.distance_km), " km") : "Not recorded",
              routeCompletedAt(route) ? formatDate(routeCompletedAt(route)) : "-",
            ];
          })
        : [["No routes in selected period", "-", "0/0", "-", "-", "-"]],
    styles: { fontSize: 7.8, cellPadding: 2, overflow: "linebreak" },
    headStyles: { fillColor: [16, 185, 129], textColor: 255 },
    theme: "grid",
  });
  y = (doc as AutoTableDoc).lastAutoTable.finalY + 8;

  if (reportsInRange.length > 0 && y < 238) {
    y = sectionTitle(doc, "Recent Field Issues", y);
    autoTable(doc, {
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      head: [["Issue", "Status", "Priority", "Location", "Reported"]],
      body: reportsInRange
        .sort((a, b) => priorityRank(b) - priorityRank(a) || new Date(b.created_at).getTime() - new Date(a.created_at).getTime())
        .slice(0, 5)
        .map((report) => [
          truncate(formatReportType(report), 28),
          labelReportStatus(report.status),
          report.priority ? labelReportStatus(report.priority) : "Normal",
          truncate(report.location ?? "Not recorded", 36),
          formatDate(report.created_at),
        ]),
      styles: { fontSize: 7.5, cellPadding: 2, overflow: "linebreak" },
      headStyles: { fillColor: [59, 130, 246], textColor: 255 },
      theme: "grid",
    });
    y = (doc as AutoTableDoc).lastAutoTable.finalY + 8;
  }

  if (routesInRange.length === 0 && reportsInRange.length === 0 && deliveriesInRange.length === 0) {
    y = sectionTitle(doc, "No Recorded Activity", y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(75, 85, 99);
    doc.text("This driver has no routes, stops, or field reports in the selected period.", MARGIN, y);
  }

  applyFooters(doc, exportTimestamp);

  const safeDate = exportTimestamp.toISOString().slice(0, 10);
  const safeDriver = driver.name.replace(/[^a-z0-9]+/gi, "-").replace(/(^-|-$)/g, "") || "driver";
  doc.save(`${safeDriver}-operational-report-${safeDate}.pdf`);
}
